clone_depth: 50

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%USERPROFILE%\.cache\matplotlib'

environment:
  matrix:
    - PYTHON: C:\Miniconda36
      PYTHON_VERSION: 3.6
    - PYTHON: C:\Miniconda37
      PYTHON_VERSION: 3.7

platform:
    - x86
    - x64

matrix:
  fast_finish: true

install:
  - if "%PLATFORM%" == "x86" set PATH=%PYTHON%\bin;%PYTHON%\Scripts;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=%PYTHON%-x64\bin;%PYTHON%-x64\Scripts;%PATH%
  - conda config --set always_yes yes
  - conda update -q conda
  - conda install -q python=%PYTHON_VERSION% setuptools numpy scipy pandas pyodbc psycopg2 seaborn
  - conda info -a
  - python setup.py install

test_script:
  - python -c 'import enviropy; enviropy.__version__;'    

build: off
